name: Lint

on: push

jobs:
  lint:
    name: Run Hadolint and ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Lint Dockerfile
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          verbose: true
          ignore: DL3018

      - name: Lint shell script
        uses: ludeeus/action-shellcheck@2.0.0
